Repository lxmn-22/Leetcode-Questions, pull requests merged in 2024-11, with the labels that each got.

#47 [Java]: DCC
  Java-Solutions/Easy/DeleteCharactersToMakeFancyString/DeleteCharactersToMakeFancyString.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted, Leetcode-DCC

#48 [Java]: DCC
  Java-Solutions/Easy/CircularSentence/CircularSentence.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted, Leetcode-DCC

#49 [Java]: DCC
  Java-Solutions/Medium/StringCompressionIII/StringCompressionIII.java
Labels: Leetcode-DCC

#50 [Java]: DCC
  Java-Solutions/Medium/MinimumNumberOfChangesToMakeBinaryStringBeautiful/MinimumNumberOfChangesToMakeBinaryStringBeautiful.java
Labels: Leetcode-DCC

#51 [Java]: DCC
  Java-Solutions/Medium/FindIfArrayCanBeSorted/FindIfArrayCanBeSorted.java
Labels: Leetcode-DCC

#52 [Java]: DCC
  Java-Solutions/Medium/LargestCombinationWithBitwiseANDgreaterThanZero/LargestCombinationWithBitwiseANDgreaterThanZero.java
Labels: Leetcode-DCC

#53 [Java]: DCC
  Java-Solutions/Medium/MaximumXORforEachQuery/MaximumXORforEachQuery.java
Labels: Leetcode-DCC

#54 [Java]: DCC
  Java-Solutions/Medium/MinimumArrayEnd/MinimumArrayEnd.java
Labels: Leetcode-DCC

#56 [Java]: DCC
  Java-Solutions/Medium/ShortestSubarrayWithORatLeastKii/ShortestSubarrayWithORatLeastKii.java
Labels: Leetcode-DCC

#58 [Java]: DCC
  Java-Solutions/Medium/PrimeSubtractionOperation/PrimeSubtractionOperation.java
Labels: Leetcode-DCC

#59 [TS]: Prime Subtraction Operation
  Typescript-Solutions/src/2601.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: Leetcode-DCC

#62 [DCC]: Leetcode
  Java-Solutions/Medium/MostBeautifulItemForEachQuery/MostBeautifulItemForEachQuery.java
  Typescript-Solutions/src/13.ts
  Typescript-Solutions/src/2070.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: Leetcode-DCC

#63 [DCC]: Leetcode
  Java-Solutions/Medium/CountTheNumberOfFairPairs/CountTheNumberOfFairPairs.java
  Typescript-Solutions/src/14.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: Leetcode-DCC

#64 [DCC]: Leetcode
  Java-Solutions/Medium/MinimizedMaximumOfProductsDistributedToAnyStore/MinimizedMaximumOfProductsDistributedToAnyStore.java
  Typescript-Solutions/src/20.ts
  Typescript-Solutions/src/2064.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: Leetcode-DCC

#65 [DCC]: Leetcode
  Java-Solutions/Medium/ShortestSubarrayToBeRemovedToMakeArraySorted/ShortestSubarrayToBeRemovedToMakeArraySorted.java
  Typescript-Solutions/src/1574.ts
  Typescript-Solutions/src/21.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#66 [DCC]: Leetcode
  Java-Solutions/Medium/FindThePowerOfKSizeSubarraysI/FindThePowerOfKSizeSubarraysI.java
  Typescript-Solutions/src/26.ts
  Typescript-Solutions/src/3254.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#67 [DCC]: Leetcode
  Java-Solutions/Hard/ShortestSubarrayWithSumAtLeastK/ShortestSubarrayWithSumAtLeastK.java
  Typescript-Solutions/src/27.ts
  Typescript-Solutions/src/862.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#69 [DCC]: Leetcode
  Java-Solutions/Medium/MaximumSumOfDistinctSubarraysWithLengthK/MaximumSumOfDistinctSubarraysWithLengthK.java
  Typescript-Solutions/src/2461.ts
  Typescript-Solutions/src/35.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#70 [DCC]: Leetcode
  Java-Solutions/Medium/TakeKofEachCharacterFromLeftAndRight/TakeKofEachCharacterFromLeftAndRight.java
  Typescript-Solutions/src/2516.ts
  Typescript-Solutions/src/58.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#71 [DCC]: Leetcode
  Java-Solutions/Medium/CountUnguardedCellsInTheGrid/CountUnguardedCellsInTheGrid.java
  Typescript-Solutions/src/2257.ts
  Typescript-Solutions/src/66.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#72 [DCC]: Leetcode
  Java-Solutions/Medium/FlipColumnsForMaximumNumberOfEqualRows/FlipColumnsForMaximumNumberOfEqualRows.java
  Typescript-Solutions/src/1072.ts
  Typescript-Solutions/src/1861.ts
  Typescript-Solutions/src/67.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#73 [DCC]: Leetcode
  Java-Solutions/Medium/MaximumMatrixSum/MaximumMatrixSum.java
  Typescript-Solutions/src/1975.ts
  Typescript-Solutions/src/69.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#74 [DCC]: Leetcode
  Java-Solutions/Hard/SlidingPuzzle/SlidingPuzzle.java
  Typescript-Solutions/src/70.ts
  Typescript-Solutions/src/773.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#75 [DCC]: Leetcode
  Typescript-Solutions/src/83.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#76 feat(README): Add Introduction, Summmary, Contributors
  Java-Solutions/Easy/Ques:2441/LargestPositiveIntegerThatExistsWithItsNegative.java
  README.md
  Typescript-Solutions/package-lock.json
  Typescript-Solutions/package.json
Labels: enhancement

#78 [DCC]: Leetcode
  Typescript-Solutions/src/88.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#80 [DCC]: Leetcode
  Java-Solutions/Hard/MinimumTimeToVisitACellInAGrid/MinimumTimeToVisitACellInAGrid.java
  Typescript-Solutions/src/100.ts
  Typescript-Solutions/src/2577.ts
  Typescript-Solutions/src/94.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC

#81 [DCC]: Leetcode
  Java-Solutions/Hard/ValidArrangementOfPairs/ValidArrangementOfPairs.java
  Typescript-Solutions/src/118.ts
  Typescript-Solutions/src/2097.ts
  Typescript-Solutions/tsconfig.tsbuildinfo
Labels: enhancement, Leetcode-DCC
