Repository lxmn-22/Leetcode-Questions, pull requests merged in 2024-10, with the labels that each got.

#12 [Java]: Binary Tree
  Java-Solutions/Medium/CousinsInBinaryTreeII/CousinsInBinaryTreeII.java
Labels: enhancement

#13 [Java]: Binary Search
  Java-Solutions/Medium/FindMinimumInRotatedSortedArray/FindMinimumInRotatedSortedArray.java
Labels: enhancement

#14 [Java]: Backtracking
  Java-Solutions/Hard/NQueens/NQueens.java
Labels: enhancement

#15 [Java]: Linked List
  Java-Solutions/Easy/IntersectionOfTwoLinkedLists/IntersectionOfTwoLinkedLists.java
Labels: enhancement

#16 [Java]: Linked List
  Java-Solutions/Medium/LRUCache/LRUCache.java
Labels: enhancement

#17 [Java]: Linked List
  Java-Solutions/Medium/LinkedListCycleII/LinkedListCycleII.java
Labels: enhancement

#18 [Java]: Linked List
  Java-Solutions/Medium/SwapNodesInPairs/SwapNodesInPairs.java
Labels: enhancement

#19 [Java]: Linked List
  Java-Solutions/Medium/CopyListWithRandomPointer/CopyListWithRandomPointer.java
Labels: enhancement

#20 [Java]: Linked List
  Java-Solutions/Hard/ReverseNodesInKGroup/ReverseNodesInKGroup.java
Labels: enhancement

#21 [Java]: Linked List
  Java-Solutions/Hard/MergeKSortedLists/MergeKSortedLists.java
Labels: enhancement

#22 [Java]: Binary Tree
  Java-Solutions/Medium/KthSmallestElementInBST/KthSmallestElementInBST.java
Labels: enhancement

#23 [Java]: Binary Tree
  Java-Solutions/Medium/FlattenBinaryTreeToLinkedList/FlattenBinaryTreeToLinkedList.java
Labels: enhancement

#26 [Java]: Binary Tree
  Java-Solutions/Medium/FlipEquivalentBinaryTrees/FlipEquivalentBinaryTrees.java
Labels: enhancement

#27 [Java]: Binary Tree
  Java-Solutions/Medium/ValidateBinarySearchTree/ValidateBinarySearchTree.java
Labels: enhancement

#28 [Java]: Binary Tree
  Java-Solutions/Medium/BinaryTreeLevelOrderTraversal/BinaryTreeLevelOrderTraversal.java
Labels: enhancement

#29 [Java]: Binary Tree
  Java-Solutions/Medium/ConstructBinaryTreeFromPreorderAndInorderTraversal/ConstructBinaryTreeFromPreorderAndInorderTraversal.java
Labels: enhancement

#30 [Java]: Daily Coding Challenge
  Java-Solutions/Medium/RemoveSubFoldersFromTheFileSystem/RemoveSubFoldersFromTheFileSystem.java
Labels: enhancement

#31 [Java]: Daily Coding Challenge
  Java-Solutions/Hard/HeightOfBinaryTreeAfterSubtreeRemovalQueries/HeightOfBinaryTreeAfterSubtreeRemovalQueries.java
Labels: enhancement

#33 [Java]: Daily Coding Challenge
  Java-Solutions/Medium/CountSquareSubmatricesWithAllOnes/CountSquareSubmatricesWithAllOnes.java
Labels: enhancement

#34 [Java]: Daily Coding Challenge
  Java-Solutions/Medium/LongestSquareStreakInAnArray/LongestSquareStreakInAnArray.java
Labels: enhancement

#36 [Java]: Array
  Java-Solutions/Medium/Search2Dmatrix/Search2Dmatrix.java
Labels: Leetcode-DCC

#37 [Java]: Array
  Java-Solutions/Hard/BinaryTreeMaximumPathSum/BinaryTreeMaximumPathSum.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted, Leetcode-DCC

#38 [Java]: Daily Coding Challenge
  Java-Solutions/Medium/MaximumNumberOfMovesInGrid/MaximumNumberOfMovesInGrid.java
Labels: enhancement, Hacktoberfest2024-accepted, Leetcode-DCC

#39 [Java]: Daily Coding Challenge
  Java-Solutions/Hard/MinimumNumberOfRemovalsToMakeMountainArray/MinimumNumberOfRemovalsToMakeMountainArray.java
Labels: enhancement, hacktoberfest2024, Hacktoberfest2024-accepted, Leetcode-DCC

#40 [Java]: Daily Coding Challenge
  Java-Solutions/Hard/MinimumTotalDistanceTraveled/MinimumTotalDistanceTraveled.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted, Leetcode-DCC

#41 New leet code question 1405
  Java-Solutions/Medium/1405/Question.md
  Java-Solutions/Medium/1405/Solution.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted

#42 Create LetterCobinationOfPhoneNumber.java
  Java-Solutions/Medium/17/LetterCobinationOfPhoneNumber.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted

#44 Create ConstructTheMinimumBitwiseArray.java
  Java-Solutions/Easy/3314/ConstructTheMinimumBitwiseArray.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted

#43 Create Pow(x,n).java
  Java-Solutions/Medium/50/Pow(x,n).java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted

#45 Create MakeArrayZeroBySubtractingEqualAmmounts.java
  Java-Solutions/Easy/2357/MakeArrayZeroBySubtractingEqualAmmounts.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted

#46 Update MakeArrayZeroBySubtractingEqualAmmounts.java
  Java-Solutions/Easy/2357/MakeArrayZeroBySubtractingEqualAmmounts.java
Labels: hacktoberfest2024, Hacktoberfest2024-accepted
